### ISSUE TITLE
Stock errors

### ISSUE THREAD

**Issue by Sonja-Erst-Holz** [wayfair-contribs/plentymarkets-plugin#210]
What is wrong with Wayfair-Plenty-Plugin?

Object
full:""
exceptionType:"Wayfair\Core\Exceptions\InventorySyncInProgressException"
errorMessage:"An Inventory Sync is in progress, preventing this one from starting."
stackTrace:"#0 plugins/sets/1/builds/57b7aa07cecf4d1aeff845f992f5cb19/Wayfair/src/Cron/InventorySyncCron.php(58): Wayfair\Services\InventoryUpdateService->sync(false)
#1 [internal function]: Wayfair\Cron\InventorySyncCron->handle()
#2 /laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#3 /laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#5 /laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Plenty\Application), Array, Object(Closure))
#6 /laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Plenty\Application), Array, Array, NULL)
#7 /Modules/Cron/Services/CronService.php(34): Illuminate\Container\Container->call(Array)
#8 /Modules/Cron/Commands/RunCronJob.php(49): Plenty\Modules\Cron\Services\CronService->execute('Wayfair\\Cron\\In...')
#9 [internal function]: Plenty\Modules\Cron\Commands\RunCronJob->handle()
#10 /laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#11 /laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#13 /laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Plenty\Application), Array, Object(Closure))
#14 /laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Plenty\Application), Array, Array, NULL)
#15 /laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#16 /symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /symfony/console/Application.php(1005): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(Plenty\Modules\Cron\Commands\RunCronJob), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 plenty/artisan(28): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}"
Wayfair Plugin Version:"1.1.6"
Trigger:"cli: artisan cron:run"

**Comment by jhoule86** [comment]
@Sonja-Erst-Holz the details you provided appear to match a known issue: https://github.com/wayfair-contribs/plentymarkets-plugin/issues/207.

**Comment by jhoule86** [comment]
@Sonja-Erst-Holz as the "Bug Report" template was not used when filing this issue, there are some details missing that would help us investigate your situation, such as which organization you work for and how Wayfair may contact you.
If you are uncomfortable posting that information on GitHub, please reach out to erpsupport@wayfair.com and reference this GitHub issue.

**Comment by Sonja-Erst-Holz** [comment]
Hi Jeff,

i reported all our error logs from plenty directly per Mail to ***@***.***



Mit freundlichen Grüßen

i. A. Sonja Brosch
E-Commerce

Erst-Holz®  - die Marke für gute Holzprodukte
Steinhaus Handelsges. mbH & Co. KG
Schauerödstraße 21
D-94152 Vornbach/Neuhaus

Tel.  08503 - 92 454-0
Fax  08503 - 92 454-29
mailto: ***@***.******@***.***>
webshop: www.erst-holz.de<http://www.erst-holz.de/>

Geschf.: Jadwiga Steinhaus
Register: Passau HRA 12807
Ust.-ID-Nr. DE 300 839 373



Von: Jeff Houle ***@***.***
Gesendet: Donnerstag, 8. April 2021 17:36
An: wayfair-contribs/plentymarkets-plugin ***@***.***>
Cc: Erst-Holz admin ***@***.***>; Mention ***@***.***>
Betreff: Re: [wayfair-contribs/plentymarkets-plugin] Stock errors (#210)


@Sonja-Erst-Holz<https://github.com/Sonja-Erst-Holz> as the "Bug Report" template was not used when filing this issue, there are some details missing that would help Wayfair investigate your situation, such as which organization you work for and how Wayfair may contact you.
If you are uncomfortable posting that information on GitHub, please reach out to ***@***.******@***.***> and reference this GitHub issue.
